### ISSUE TITLE
ESISharp should support endpoint caching

### ISSUE THREAD

**Issue by tomcur** [wranders/ESISharp#23]
EVE ESI does not have rate limiting -- it relies on client applications [caching endpoints](http://eveonline-third-party-documentation.readthedocs.io/en/latest/esi/#rate-limiting).

It would be helpful if ESISharp supports caching, e.g. through supplying a .NET framework `System.Runtime.Caching.ObjectCache` class to ESISharp.

**Comment by tomcur** [comment]
A useful concrete implementation of this class is the [FileCache](https://www.nuget.org/packages/FileCache/) package.

**Comment by wranders** [comment]
Ah yes, caching was on the ToDo list, but never got around to figuring out a good implementation.
Thanks for linking that package. Re-added to the ToDo list.

**Comment by wranders** [comment]
After getting back into the code, I remembered why I abandoned implementing built-in caching.

The [EsiResponse](../blob/master/ESISharp/Object/EsiResponse.cs) object also contains [EsiResponseHeaders](../blob/master/ESISharp/Object/EsiResponse.cs#L34), which stores all the pertinent information for caching. I did it this way so that the app developer could choose their own caching scheme and not have to worry about maintaining an outside cache alongside whatever they implemented themselves.

I thought then that this was a reasonable solution. Would you agree?

**Comment by wranders** [comment]
I'd be open to making a caching library specifically for ESISharp as a separate project after I'm done validating everything, but I think integrating that is a bit out of scope for an interface.

**Comment by tomcur** [comment]
I agree that app developers should not have to worry about maintaining an outside cache.

However, I also think it would be good for ESISharp to support caching using any class with, e.g., the `System.Runtime.Caching.ObjectCache` interface. The app developer can then choose which, if any, cache to use. It then becomes very easy for the developer to supply the built-in `MemoryCache`, or the `FileCache` I linked previously.

**Comment by tomcur** [comment]
A different EVE API library (but for CREST instead of ESI) handles it that way as well. See: https://github.com/3rdpartyeve/perry#cache

**Comment by wranders** [comment]
Took a while to be able to get back to it, but 9d0f0ef0ce2731d6e3605833b68d5a36c6bdd27a added an initial attempt at caching. It follows your suggestion on taking any implementation of `ObjectCache`. I haven't tested expiration, and for now it's hard set to `AbsoluteExpire` on the time returned in the Content header. At a later point I'll put in a control for data retention, but it *should* work for now.

```csharp
var a = new ESISharp.Public();
var m = new MemoryCache("cache");
a.CachingEnabled(m);
```

**Comment by tomcur** [comment]
Awesome! Looks good.

I think using the `Expires` header is the most common use-case anyway. At least it's how I would like to use it myself.
