### ISSUE TITLE
sample project

### ISSUE THREAD

**Issue by martijn805** [wranders/ESISharp#31]
Hi,

Would it be possible to add a small example file to the solution on how to create an authenticated request and retrieve the data from ESI?
I have not done much programming in the past few years and getting the environment setup correctly is proving a bit difficult, having an example would be very helpful.

With regards,

Martijn

**Comment by wranders** [comment]
Oh, definitely. Examples are planned for the documentation, but I've got to finish playing catch-up before I can work on that.

In the mean time, I gave an example in another issue ([#16 Code Example](https://github.com/wranders/ESISharp/issues/16#issuecomment-316720135)) that should still be valid as long as you're using the `master` branch. (Just make sure to to use your `ClientID`, `SecretKey`, and directory path for `EveSSOAuthRouter.exe`)

But, please keep in mind that `master` is at least 6 months out of date. Most endpoints are available, but almost all of the new `Corporation` paths are missing. `dev` is about half updated, but expect things to break if you're using it.

**Comment by wranders** [comment]
If you need more specific examples, please ask. 
Writing some out here is a good place to start gathering them for the docs later.

**Comment by martijn805** [comment]
edit: my apologies, seems a reboot of my pc seems to have fixed the issue. Too many changes made the system a bit unstable.

Thanks for your quick response.
I think I'm almost there, I switched to the dev version and am able to get to the point where I can launch the EveSSOAuthRouter.exe. It gives me a code and a state, but I get an security error from the Client.Connect() line:
Unhandled Exception: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at System.IO.Pipes.NamedPipeClientStream.Connect()
   at EveSSOAuthRouter.Program.Main(String[] args)
I tried changing the security settings and moving the .exe around but it seems I'm still missing a step. Registry keys seem in order as well.

**Comment by wranders** [comment]
Oh! I completely forgot that could happen. I'll be adding this to another `ToDo`.

The communication between the AuthRouter and the library uses named communication tunnels.  If the tunnel was opened but not closed for some reason, the next time you try to open that tunnel, you'll get that error. 

If it happens again, open up your task manager and force-quit the `EveSSOAuthRouter.exe`. That should close the tunnel and make it available for use again.
