### ISSUE TITLE
When opening SLN I get the following Build Errors

### ISSUE THREAD

**Issue by Grzy7316** [wranders/ESISharp#37]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'CharacterFactionWarfare' could not be found (are you missing a using directive or an assembly reference?)	ESISharp	E:\EVE API\ESISHARP\ESISharp\Path\Character.cs	100	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'CharacterFactionWarfare' could not be found (are you missing a using directive or an assembly reference?)	ESISharp	E:\EVE API\ESISHARP\ESISharp\Path\Character.cs	136	Active
Error	CS0118	'FactionWarfare' is a type but is used like a variable	ESISharp	E:\EVE API\ESISHARP\ESISharp\Path\Corporation.cs	103	Active
Error	CS0246	The type or namespace name 'CorporationFactionWarfare' could not be found (are you missing a using directive or an assembly reference?)	ESISharp	E:\EVE API\ESISHARP\ESISharp\Path\Corporation.cs	103	Active

**Comment by wranders** [comment]
Interesting. 
Looks like I forgot to build after I added the Character and Corporation Faction Warfare files, so the CSProj file didn't include the new references.

Fixed with https://github.com/wranders/ESISharp/commit/2e030dcfcd4e7b9c9ef2536279db07ff3d30d5dd
